name: flutter_native_image
description: A Flutter plugin for image manipulation using native iOS/Android APIs. Supports image compression, resizing, cropping, and property retrieval.
version: 0.0.7
homepage: https://konseben.dev
issue_tracker: https://github.com/btastic/flutter_native_image/issues

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
      ios:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
